# Generated by Django 5.2.4 on 2025-07-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_auth_provider_user_is_online_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_icon.png', null=True, upload_to='user/avatar/', verbose_name='avatar'),
        ),
    ]
