# Generated by Django 4.2.3 on 2024-07-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_breezeaccount_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="percentageinstrument",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="percentage",
                to="core.subscribedinstruments",
            ),
        ),
    ]
