# Generated by Django 5.2.3 on 2025-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tick_ltq'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exchanges',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
