# Generated by Django 5.2.4 on 2025-07-07 14:02

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exchanges_created_at_exchanges_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ['date']},
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['instrument', '-date'], name='idx_candle_instr_date_desc'),
        ),
        migrations.AddIndex(
            model_name='candle',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='brin_candle_date'),
        ),
    ]
