# Generated by Django 4.2.3 on 2024-02-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserOtps",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_teacher",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
    ]
