# Generated by Django 4.2.3 on 2024-07-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_percentageinstrument_instrument"),
    ]

    operations = [
        migrations.AddField(
            model_name="candle",
            name="volume",
            field=models.FloatField(null=True),
        ),
    ]
