name: "Backend"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "backend/**/pyproject.toml"

      - name: Install dependencies
        working-directory: ./backend
        run: uv sync --dev --frozen

      - name: Run Black (formatting check)
        working-directory: ./backend
        run: uvx black --check --diff .

      - name: Run Ruff (linting)
        working-directory: ./backend
        run: uvx ruff check --output-format=github .

      - name: Run Tests
        working-directory: ./backend
        run: uv run pytest --verbose --tb=short

      - name: Backend Quality Summary
        if: always()
        run: |
          echo "### Backend Code Quality Results" >> $GITHUB_STEP_SUMMARY
          echo "- Python version: 3.13" >> $GITHUB_STEP_SUMMARY
          echo "- Black formatting: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Ruff linting: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tests: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
