name: "Frontend"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Prettier (formatting check)
        working-directory: ./frontend
        run: npm run format:check

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      - name: Type check
        working-directory: ./frontend
        run: npm run type-check

      - name: Run Tests
        working-directory: ./frontend
        run: npm run test:run -- --maxWorkers=20%

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Frontend Quality Summary
        if: always()
        run: |
          echo "### Frontend Code Quality Results" >> $GITHUB_STEP_SUMMARY
          echo "- Node.js version: ${{ matrix.node-version }}" >> $GITHUB_STEP_SUMMARY
          echo "- Prettier formatting: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- ESLint: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Type check: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tests: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- Build: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: matrix.node-version == '20'
        with:
          file: ./frontend/coverage/coverage-final.json
          flags: frontend
          name: frontend-coverage
